export {getData, FETCHING_WEBCAM_DATA_START} from './webCamActions';
// export const FETCHING_WEBCAM_DATA_SUCCESS = 'FETCHING_WEBCAM_DATA_SUCCESS';
// export const FETCHING_WEBCAM_DATA_FAILURE = 'FETCHING_WEBCAM_DATA_FAIL';
